/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { CarritoWhereUniqueInput } from "../../carrito/base/CarritoWhereUniqueInput";
import { Type } from "class-transformer";
import { CarritoCreateNestedManyWithoutUsuariosInput } from "./CarritoCreateNestedManyWithoutUsuariosInput";
import { OrdenDeCompraCreateNestedManyWithoutUsuariosInput } from "./OrdenDeCompraCreateNestedManyWithoutUsuariosInput";
import { PedidoCreateNestedManyWithoutUsuariosInput } from "./PedidoCreateNestedManyWithoutUsuariosInput";
import { EnumUsuarioRol } from "./EnumUsuarioRol";

@InputType()
class UsuarioCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  apellido?: string | null;

  @ApiProperty({
    required: false,
    type: () => CarritoWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CarritoWhereUniqueInput)
  @IsOptional()
  @Field(() => CarritoWhereUniqueInput, {
    nullable: true,
  })
  carrito?: CarritoWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => CarritoCreateNestedManyWithoutUsuariosInput,
  })
  @ValidateNested()
  @Type(() => CarritoCreateNestedManyWithoutUsuariosInput)
  @IsOptional()
  @Field(() => CarritoCreateNestedManyWithoutUsuariosInput, {
    nullable: true,
  })
  carritos?: CarritoCreateNestedManyWithoutUsuariosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nombre?: string | null;

  @ApiProperty({
    required: false,
    type: () => OrdenDeCompraCreateNestedManyWithoutUsuariosInput,
  })
  @ValidateNested()
  @Type(() => OrdenDeCompraCreateNestedManyWithoutUsuariosInput)
  @IsOptional()
  @Field(() => OrdenDeCompraCreateNestedManyWithoutUsuariosInput, {
    nullable: true,
  })
  ordenDeCompras?: OrdenDeCompraCreateNestedManyWithoutUsuariosInput;

  @ApiProperty({
    required: false,
    type: () => PedidoCreateNestedManyWithoutUsuariosInput,
  })
  @ValidateNested()
  @Type(() => PedidoCreateNestedManyWithoutUsuariosInput)
  @IsOptional()
  @Field(() => PedidoCreateNestedManyWithoutUsuariosInput, {
    nullable: true,
  })
  pedidos?: PedidoCreateNestedManyWithoutUsuariosInput;

  @ApiProperty({
    required: false,
    enum: EnumUsuarioRol,
  })
  @IsEnum(EnumUsuarioRol)
  @IsOptional()
  @Field(() => EnumUsuarioRol, {
    nullable: true,
  })
  rol?: "Option1" | null;
}

export { UsuarioCreateInput as UsuarioCreateInput };
