/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsDate,
  IsEnum,
} from "class-validator";
import { Carrito } from "../../carrito/base/Carrito";
import { Type } from "class-transformer";
import { OrdenDeCompra } from "../../ordenDeCompra/base/OrdenDeCompra";
import { Pedido } from "../../pedido/base/Pedido";
import { EnumUsuarioRol } from "./EnumUsuarioRol";

@ObjectType()
class Usuario {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  apellido!: string | null;

  @ApiProperty({
    required: false,
    type: () => Carrito,
  })
  @ValidateNested()
  @Type(() => Carrito)
  @IsOptional()
  carrito?: Carrito | null;

  @ApiProperty({
    required: false,
    type: () => [Carrito],
  })
  @ValidateNested()
  @Type(() => Carrito)
  @IsOptional()
  carritos?: Array<Carrito>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email!: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nombre!: string | null;

  @ApiProperty({
    required: false,
    type: () => [OrdenDeCompra],
  })
  @ValidateNested()
  @Type(() => OrdenDeCompra)
  @IsOptional()
  ordenDeCompras?: Array<OrdenDeCompra>;

  @ApiProperty({
    required: false,
    type: () => [Pedido],
  })
  @ValidateNested()
  @Type(() => Pedido)
  @IsOptional()
  pedidos?: Array<Pedido>;

  @ApiProperty({
    required: false,
    enum: EnumUsuarioRol,
  })
  @IsEnum(EnumUsuarioRol)
  @IsOptional()
  @Field(() => EnumUsuarioRol, {
    nullable: true,
  })
  rol?: "Option1" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Usuario as Usuario };
