/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Usuario } from "./Usuario";
import { UsuarioCountArgs } from "./UsuarioCountArgs";
import { UsuarioFindManyArgs } from "./UsuarioFindManyArgs";
import { UsuarioFindUniqueArgs } from "./UsuarioFindUniqueArgs";
import { CreateUsuarioArgs } from "./CreateUsuarioArgs";
import { UpdateUsuarioArgs } from "./UpdateUsuarioArgs";
import { DeleteUsuarioArgs } from "./DeleteUsuarioArgs";
import { CarritoFindManyArgs } from "../../carrito/base/CarritoFindManyArgs";
import { Carrito } from "../../carrito/base/Carrito";
import { OrdenDeCompraFindManyArgs } from "../../ordenDeCompra/base/OrdenDeCompraFindManyArgs";
import { OrdenDeCompra } from "../../ordenDeCompra/base/OrdenDeCompra";
import { PedidoFindManyArgs } from "../../pedido/base/PedidoFindManyArgs";
import { Pedido } from "../../pedido/base/Pedido";
import { UsuarioService } from "../usuario.service";
@graphql.Resolver(() => Usuario)
export class UsuarioResolverBase {
  constructor(protected readonly service: UsuarioService) {}

  async _usuariosMeta(
    @graphql.Args() args: UsuarioCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Usuario])
  async usuarios(
    @graphql.Args() args: UsuarioFindManyArgs
  ): Promise<Usuario[]> {
    return this.service.usuarios(args);
  }

  @graphql.Query(() => Usuario, { nullable: true })
  async usuario(
    @graphql.Args() args: UsuarioFindUniqueArgs
  ): Promise<Usuario | null> {
    const result = await this.service.usuario(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Usuario)
  async createUsuario(
    @graphql.Args() args: CreateUsuarioArgs
  ): Promise<Usuario> {
    return await this.service.createUsuario({
      ...args,
      data: {
        ...args.data,

        carrito: args.data.carrito
          ? {
              connect: args.data.carrito,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Usuario)
  async updateUsuario(
    @graphql.Args() args: UpdateUsuarioArgs
  ): Promise<Usuario | null> {
    try {
      return await this.service.updateUsuario({
        ...args,
        data: {
          ...args.data,

          carrito: args.data.carrito
            ? {
                connect: args.data.carrito,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Usuario)
  async deleteUsuario(
    @graphql.Args() args: DeleteUsuarioArgs
  ): Promise<Usuario | null> {
    try {
      return await this.service.deleteUsuario(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Carrito], { name: "carritos" })
  async findCarritos(
    @graphql.Parent() parent: Usuario,
    @graphql.Args() args: CarritoFindManyArgs
  ): Promise<Carrito[]> {
    const results = await this.service.findCarritos(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [OrdenDeCompra], { name: "ordenDeCompras" })
  async findOrdenDeCompras(
    @graphql.Parent() parent: Usuario,
    @graphql.Args() args: OrdenDeCompraFindManyArgs
  ): Promise<OrdenDeCompra[]> {
    const results = await this.service.findOrdenDeCompras(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Pedido], { name: "pedidos" })
  async findPedidos(
    @graphql.Parent() parent: Usuario,
    @graphql.Args() args: PedidoFindManyArgs
  ): Promise<Pedido[]> {
    const results = await this.service.findPedidos(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Carrito, {
    nullable: true,
    name: "carrito",
  })
  async getCarrito(@graphql.Parent() parent: Usuario): Promise<Carrito | null> {
    const result = await this.service.getCarrito(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
