/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { CarritoWhereUniqueInput } from "../../carrito/base/CarritoWhereUniqueInput";
import { Type } from "class-transformer";
import { CarritoUpdateManyWithoutUsuariosInput } from "./CarritoUpdateManyWithoutUsuariosInput";
import { OrdenDeCompraUpdateManyWithoutUsuariosInput } from "./OrdenDeCompraUpdateManyWithoutUsuariosInput";
import { PedidoUpdateManyWithoutUsuariosInput } from "./PedidoUpdateManyWithoutUsuariosInput";
import { EnumUsuarioRol } from "./EnumUsuarioRol";

@InputType()
class UsuarioUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  apellido?: string | null;

  @ApiProperty({
    required: false,
    type: () => CarritoWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CarritoWhereUniqueInput)
  @IsOptional()
  @Field(() => CarritoWhereUniqueInput, {
    nullable: true,
  })
  carrito?: CarritoWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => CarritoUpdateManyWithoutUsuariosInput,
  })
  @ValidateNested()
  @Type(() => CarritoUpdateManyWithoutUsuariosInput)
  @IsOptional()
  @Field(() => CarritoUpdateManyWithoutUsuariosInput, {
    nullable: true,
  })
  carritos?: CarritoUpdateManyWithoutUsuariosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nombre?: string | null;

  @ApiProperty({
    required: false,
    type: () => OrdenDeCompraUpdateManyWithoutUsuariosInput,
  })
  @ValidateNested()
  @Type(() => OrdenDeCompraUpdateManyWithoutUsuariosInput)
  @IsOptional()
  @Field(() => OrdenDeCompraUpdateManyWithoutUsuariosInput, {
    nullable: true,
  })
  ordenDeCompras?: OrdenDeCompraUpdateManyWithoutUsuariosInput;

  @ApiProperty({
    required: false,
    type: () => PedidoUpdateManyWithoutUsuariosInput,
  })
  @ValidateNested()
  @Type(() => PedidoUpdateManyWithoutUsuariosInput)
  @IsOptional()
  @Field(() => PedidoUpdateManyWithoutUsuariosInput, {
    nullable: true,
  })
  pedidos?: PedidoUpdateManyWithoutUsuariosInput;

  @ApiProperty({
    required: false,
    enum: EnumUsuarioRol,
  })
  @IsEnum(EnumUsuarioRol)
  @IsOptional()
  @Field(() => EnumUsuarioRol, {
    nullable: true,
  })
  rol?: "Option1" | null;
}

export { UsuarioUpdateInput as UsuarioUpdateInput };
