/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { CarritoWhereUniqueInput } from "../../carrito/base/CarritoWhereUniqueInput";
import { CarritoListRelationFilter } from "../../carrito/base/CarritoListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { OrdenDeCompraListRelationFilter } from "../../ordenDeCompra/base/OrdenDeCompraListRelationFilter";
import { PedidoListRelationFilter } from "../../pedido/base/PedidoListRelationFilter";
import { EnumUsuarioRol } from "./EnumUsuarioRol";

@InputType()
class UsuarioWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  apellido?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => CarritoWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CarritoWhereUniqueInput)
  @IsOptional()
  @Field(() => CarritoWhereUniqueInput, {
    nullable: true,
  })
  carrito?: CarritoWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => CarritoListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CarritoListRelationFilter)
  @IsOptional()
  @Field(() => CarritoListRelationFilter, {
    nullable: true,
  })
  carritos?: CarritoListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nombre?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => OrdenDeCompraListRelationFilter,
  })
  @ValidateNested()
  @Type(() => OrdenDeCompraListRelationFilter)
  @IsOptional()
  @Field(() => OrdenDeCompraListRelationFilter, {
    nullable: true,
  })
  ordenDeCompras?: OrdenDeCompraListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => PedidoListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PedidoListRelationFilter)
  @IsOptional()
  @Field(() => PedidoListRelationFilter, {
    nullable: true,
  })
  pedidos?: PedidoListRelationFilter;

  @ApiProperty({
    required: false,
    enum: EnumUsuarioRol,
  })
  @IsEnum(EnumUsuarioRol)
  @IsOptional()
  @Field(() => EnumUsuarioRol, {
    nullable: true,
  })
  rol?: "Option1";
}

export { UsuarioWhereInput as UsuarioWhereInput };
