/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UsuarioService } from "../usuario.service";
import { UsuarioCreateInput } from "./UsuarioCreateInput";
import { Usuario } from "./Usuario";
import { UsuarioFindManyArgs } from "./UsuarioFindManyArgs";
import { UsuarioWhereUniqueInput } from "./UsuarioWhereUniqueInput";
import { UsuarioUpdateInput } from "./UsuarioUpdateInput";
import { CarritoFindManyArgs } from "../../carrito/base/CarritoFindManyArgs";
import { Carrito } from "../../carrito/base/Carrito";
import { CarritoWhereUniqueInput } from "../../carrito/base/CarritoWhereUniqueInput";
import { OrdenDeCompraFindManyArgs } from "../../ordenDeCompra/base/OrdenDeCompraFindManyArgs";
import { OrdenDeCompra } from "../../ordenDeCompra/base/OrdenDeCompra";
import { OrdenDeCompraWhereUniqueInput } from "../../ordenDeCompra/base/OrdenDeCompraWhereUniqueInput";
import { PedidoFindManyArgs } from "../../pedido/base/PedidoFindManyArgs";
import { Pedido } from "../../pedido/base/Pedido";
import { PedidoWhereUniqueInput } from "../../pedido/base/PedidoWhereUniqueInput";

export class UsuarioControllerBase {
  constructor(protected readonly service: UsuarioService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Usuario })
  async createUsuario(
    @common.Body() data: UsuarioCreateInput
  ): Promise<Usuario> {
    return await this.service.createUsuario({
      data: {
        ...data,

        carrito: data.carrito
          ? {
              connect: data.carrito,
            }
          : undefined,
      },
      select: {
        apellido: true,

        carrito: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        id: true,
        nombre: true,
        rol: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Usuario] })
  @ApiNestedQuery(UsuarioFindManyArgs)
  async usuarios(@common.Req() request: Request): Promise<Usuario[]> {
    const args = plainToClass(UsuarioFindManyArgs, request.query);
    return this.service.usuarios({
      ...args,
      select: {
        apellido: true,

        carrito: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        id: true,
        nombre: true,
        rol: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Usuario })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async usuario(
    @common.Param() params: UsuarioWhereUniqueInput
  ): Promise<Usuario | null> {
    const result = await this.service.usuario({
      where: params,
      select: {
        apellido: true,

        carrito: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        id: true,
        nombre: true,
        rol: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Usuario })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUsuario(
    @common.Param() params: UsuarioWhereUniqueInput,
    @common.Body() data: UsuarioUpdateInput
  ): Promise<Usuario | null> {
    try {
      return await this.service.updateUsuario({
        where: params,
        data: {
          ...data,

          carrito: data.carrito
            ? {
                connect: data.carrito,
              }
            : undefined,
        },
        select: {
          apellido: true,

          carrito: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          email: true,
          id: true,
          nombre: true,
          rol: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Usuario })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUsuario(
    @common.Param() params: UsuarioWhereUniqueInput
  ): Promise<Usuario | null> {
    try {
      return await this.service.deleteUsuario({
        where: params,
        select: {
          apellido: true,

          carrito: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          email: true,
          id: true,
          nombre: true,
          rol: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/carritos")
  @ApiNestedQuery(CarritoFindManyArgs)
  async findCarritos(
    @common.Req() request: Request,
    @common.Param() params: UsuarioWhereUniqueInput
  ): Promise<Carrito[]> {
    const query = plainToClass(CarritoFindManyArgs, request.query);
    const results = await this.service.findCarritos(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,

        usuario: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/carritos")
  async connectCarritos(
    @common.Param() params: UsuarioWhereUniqueInput,
    @common.Body() body: CarritoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      carritos: {
        connect: body,
      },
    };
    await this.service.updateUsuario({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/carritos")
  async updateCarritos(
    @common.Param() params: UsuarioWhereUniqueInput,
    @common.Body() body: CarritoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      carritos: {
        set: body,
      },
    };
    await this.service.updateUsuario({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/carritos")
  async disconnectCarritos(
    @common.Param() params: UsuarioWhereUniqueInput,
    @common.Body() body: CarritoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      carritos: {
        disconnect: body,
      },
    };
    await this.service.updateUsuario({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/ordenDeCompras")
  @ApiNestedQuery(OrdenDeCompraFindManyArgs)
  async findOrdenDeCompras(
    @common.Req() request: Request,
    @common.Param() params: UsuarioWhereUniqueInput
  ): Promise<OrdenDeCompra[]> {
    const query = plainToClass(OrdenDeCompraFindManyArgs, request.query);
    const results = await this.service.findOrdenDeCompras(params.id, {
      ...query,
      select: {
        createdAt: true,
        estado: true,
        id: true,
        updatedAt: true,

        usuario: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/ordenDeCompras")
  async connectOrdenDeCompras(
    @common.Param() params: UsuarioWhereUniqueInput,
    @common.Body() body: OrdenDeCompraWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ordenDeCompras: {
        connect: body,
      },
    };
    await this.service.updateUsuario({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/ordenDeCompras")
  async updateOrdenDeCompras(
    @common.Param() params: UsuarioWhereUniqueInput,
    @common.Body() body: OrdenDeCompraWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ordenDeCompras: {
        set: body,
      },
    };
    await this.service.updateUsuario({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/ordenDeCompras")
  async disconnectOrdenDeCompras(
    @common.Param() params: UsuarioWhereUniqueInput,
    @common.Body() body: OrdenDeCompraWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ordenDeCompras: {
        disconnect: body,
      },
    };
    await this.service.updateUsuario({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/pedidos")
  @ApiNestedQuery(PedidoFindManyArgs)
  async findPedidos(
    @common.Req() request: Request,
    @common.Param() params: UsuarioWhereUniqueInput
  ): Promise<Pedido[]> {
    const query = plainToClass(PedidoFindManyArgs, request.query);
    const results = await this.service.findPedidos(params.id, {
      ...query,
      select: {
        adeuda: true,
        comprobante: true,
        createdAt: true,
        descripcion: true,
        estado: true,
        id: true,
        metodoDePago: true,
        restoPagado: true,
        seA: true,

        talle: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        usuario: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/pedidos")
  async connectPedidos(
    @common.Param() params: UsuarioWhereUniqueInput,
    @common.Body() body: PedidoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pedidos: {
        connect: body,
      },
    };
    await this.service.updateUsuario({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/pedidos")
  async updatePedidos(
    @common.Param() params: UsuarioWhereUniqueInput,
    @common.Body() body: PedidoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pedidos: {
        set: body,
      },
    };
    await this.service.updateUsuario({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/pedidos")
  async disconnectPedidos(
    @common.Param() params: UsuarioWhereUniqueInput,
    @common.Body() body: PedidoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pedidos: {
        disconnect: body,
      },
    };
    await this.service.updateUsuario({
      where: params,
      data,
      select: { id: true },
    });
  }
}
