/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CarritoService } from "../carrito.service";
import { CarritoCreateInput } from "./CarritoCreateInput";
import { Carrito } from "./Carrito";
import { CarritoFindManyArgs } from "./CarritoFindManyArgs";
import { CarritoWhereUniqueInput } from "./CarritoWhereUniqueInput";
import { CarritoUpdateInput } from "./CarritoUpdateInput";
import { UsuarioFindManyArgs } from "../../usuario/base/UsuarioFindManyArgs";
import { Usuario } from "../../usuario/base/Usuario";
import { UsuarioWhereUniqueInput } from "../../usuario/base/UsuarioWhereUniqueInput";

export class CarritoControllerBase {
  constructor(protected readonly service: CarritoService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Carrito })
  async createCarrito(
    @common.Body() data: CarritoCreateInput
  ): Promise<Carrito> {
    return await this.service.createCarrito({
      data: {
        ...data,

        usuario: data.usuario
          ? {
              connect: data.usuario,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,

        usuario: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Carrito] })
  @ApiNestedQuery(CarritoFindManyArgs)
  async carritos(@common.Req() request: Request): Promise<Carrito[]> {
    const args = plainToClass(CarritoFindManyArgs, request.query);
    return this.service.carritos({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,

        usuario: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Carrito })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async carrito(
    @common.Param() params: CarritoWhereUniqueInput
  ): Promise<Carrito | null> {
    const result = await this.service.carrito({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,

        usuario: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Carrito })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCarrito(
    @common.Param() params: CarritoWhereUniqueInput,
    @common.Body() data: CarritoUpdateInput
  ): Promise<Carrito | null> {
    try {
      return await this.service.updateCarrito({
        where: params,
        data: {
          ...data,

          usuario: data.usuario
            ? {
                connect: data.usuario,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,

          usuario: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Carrito })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCarrito(
    @common.Param() params: CarritoWhereUniqueInput
  ): Promise<Carrito | null> {
    try {
      return await this.service.deleteCarrito({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,

          usuario: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/usuarios")
  @ApiNestedQuery(UsuarioFindManyArgs)
  async findUsuarios(
    @common.Req() request: Request,
    @common.Param() params: CarritoWhereUniqueInput
  ): Promise<Usuario[]> {
    const query = plainToClass(UsuarioFindManyArgs, request.query);
    const results = await this.service.findUsuarios(params.id, {
      ...query,
      select: {
        apellido: true,

        carrito: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        id: true,
        nombre: true,
        rol: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/usuarios")
  async connectUsuarios(
    @common.Param() params: CarritoWhereUniqueInput,
    @common.Body() body: UsuarioWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      usuarios: {
        connect: body,
      },
    };
    await this.service.updateCarrito({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/usuarios")
  async updateUsuarios(
    @common.Param() params: CarritoWhereUniqueInput,
    @common.Body() body: UsuarioWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      usuarios: {
        set: body,
      },
    };
    await this.service.updateCarrito({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/usuarios")
  async disconnectUsuarios(
    @common.Param() params: CarritoWhereUniqueInput,
    @common.Body() body: UsuarioWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      usuarios: {
        disconnect: body,
      },
    };
    await this.service.updateCarrito({
      where: params,
      data,
      select: { id: true },
    });
  }
}
