/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Carrito } from "./Carrito";
import { CarritoCountArgs } from "./CarritoCountArgs";
import { CarritoFindManyArgs } from "./CarritoFindManyArgs";
import { CarritoFindUniqueArgs } from "./CarritoFindUniqueArgs";
import { CreateCarritoArgs } from "./CreateCarritoArgs";
import { UpdateCarritoArgs } from "./UpdateCarritoArgs";
import { DeleteCarritoArgs } from "./DeleteCarritoArgs";
import { UsuarioFindManyArgs } from "../../usuario/base/UsuarioFindManyArgs";
import { Usuario } from "../../usuario/base/Usuario";
import { CarritoService } from "../carrito.service";
@graphql.Resolver(() => Carrito)
export class CarritoResolverBase {
  constructor(protected readonly service: CarritoService) {}

  async _carritosMeta(
    @graphql.Args() args: CarritoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Carrito])
  async carritos(
    @graphql.Args() args: CarritoFindManyArgs
  ): Promise<Carrito[]> {
    return this.service.carritos(args);
  }

  @graphql.Query(() => Carrito, { nullable: true })
  async carrito(
    @graphql.Args() args: CarritoFindUniqueArgs
  ): Promise<Carrito | null> {
    const result = await this.service.carrito(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Carrito)
  async createCarrito(
    @graphql.Args() args: CreateCarritoArgs
  ): Promise<Carrito> {
    return await this.service.createCarrito({
      ...args,
      data: {
        ...args.data,

        usuario: args.data.usuario
          ? {
              connect: args.data.usuario,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Carrito)
  async updateCarrito(
    @graphql.Args() args: UpdateCarritoArgs
  ): Promise<Carrito | null> {
    try {
      return await this.service.updateCarrito({
        ...args,
        data: {
          ...args.data,

          usuario: args.data.usuario
            ? {
                connect: args.data.usuario,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Carrito)
  async deleteCarrito(
    @graphql.Args() args: DeleteCarritoArgs
  ): Promise<Carrito | null> {
    try {
      return await this.service.deleteCarrito(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Usuario], { name: "usuarios" })
  async findUsuarios(
    @graphql.Parent() parent: Carrito,
    @graphql.Args() args: UsuarioFindManyArgs
  ): Promise<Usuario[]> {
    const results = await this.service.findUsuarios(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Usuario, {
    nullable: true,
    name: "usuario",
  })
  async getUsuario(@graphql.Parent() parent: Carrito): Promise<Usuario | null> {
    const result = await this.service.getUsuario(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
