/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Carrito as PrismaCarrito,
  Usuario as PrismaUsuario,
} from "@prisma/client";

export class CarritoServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.CarritoCountArgs, "select">): Promise<number> {
    return this.prisma.carrito.count(args);
  }

  async carritos(args: Prisma.CarritoFindManyArgs): Promise<PrismaCarrito[]> {
    return this.prisma.carrito.findMany(args);
  }
  async carrito(
    args: Prisma.CarritoFindUniqueArgs
  ): Promise<PrismaCarrito | null> {
    return this.prisma.carrito.findUnique(args);
  }
  async createCarrito(args: Prisma.CarritoCreateArgs): Promise<PrismaCarrito> {
    return this.prisma.carrito.create(args);
  }
  async updateCarrito(args: Prisma.CarritoUpdateArgs): Promise<PrismaCarrito> {
    return this.prisma.carrito.update(args);
  }
  async deleteCarrito(args: Prisma.CarritoDeleteArgs): Promise<PrismaCarrito> {
    return this.prisma.carrito.delete(args);
  }

  async findUsuarios(
    parentId: string,
    args: Prisma.UsuarioFindManyArgs
  ): Promise<PrismaUsuario[]> {
    return this.prisma.carrito
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .usuarios(args);
  }

  async getUsuario(parentId: string): Promise<PrismaUsuario | null> {
    return this.prisma.carrito
      .findUnique({
        where: { id: parentId },
      })
      .usuario();
  }
}
