/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsNumber,
  Min,
  Max,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
  IsBoolean,
  ValidateNested,
} from "class-validator";

import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumPedidoEstado } from "./EnumPedidoEstado";
import { EnumPedidoMetodoDePago } from "./EnumPedidoMetodoDePago";
import { TalleWhereUniqueInput } from "../../talle/base/TalleWhereUniqueInput";
import { Type } from "class-transformer";
import { UsuarioWhereUniqueInput } from "../../usuario/base/UsuarioWhereUniqueInput";

@InputType()
class PedidoUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  adeuda?: number | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  comprobante?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  descripcion?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumPedidoEstado,
  })
  @IsEnum(EnumPedidoEstado)
  @IsOptional()
  @Field(() => EnumPedidoEstado, {
    nullable: true,
  })
  estado?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumPedidoMetodoDePago,
  })
  @IsEnum(EnumPedidoMetodoDePago)
  @IsOptional()
  @Field(() => EnumPedidoMetodoDePago, {
    nullable: true,
  })
  metodoDePago?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  restoPagado?: boolean | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  seA?: number | null;

  @ApiProperty({
    required: false,
    type: () => TalleWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TalleWhereUniqueInput)
  @IsOptional()
  @Field(() => TalleWhereUniqueInput, {
    nullable: true,
  })
  talle?: TalleWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => UsuarioWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UsuarioWhereUniqueInput)
  @IsOptional()
  @Field(() => UsuarioWhereUniqueInput, {
    nullable: true,
  })
  usuario?: UsuarioWhereUniqueInput | null;
}

export { PedidoUpdateInput as PedidoUpdateInput };
