/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { JsonFilter } from "../../util/JsonFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { EnumPedidoEstado } from "./EnumPedidoEstado";
import { StringFilter } from "../../util/StringFilter";
import { EnumPedidoMetodoDePago } from "./EnumPedidoMetodoDePago";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { TalleWhereUniqueInput } from "../../talle/base/TalleWhereUniqueInput";
import { UsuarioWhereUniqueInput } from "../../usuario/base/UsuarioWhereUniqueInput";

@InputType()
class PedidoWhereInput {
  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  adeuda?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  comprobante?: JsonFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  descripcion?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumPedidoEstado,
  })
  @IsEnum(EnumPedidoEstado)
  @IsOptional()
  @Field(() => EnumPedidoEstado, {
    nullable: true,
  })
  estado?: "Option1";

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    enum: EnumPedidoMetodoDePago,
  })
  @IsEnum(EnumPedidoMetodoDePago)
  @IsOptional()
  @Field(() => EnumPedidoMetodoDePago, {
    nullable: true,
  })
  metodoDePago?: "Option1";

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  restoPagado?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  seA?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: () => TalleWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TalleWhereUniqueInput)
  @IsOptional()
  @Field(() => TalleWhereUniqueInput, {
    nullable: true,
  })
  talle?: TalleWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => UsuarioWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UsuarioWhereUniqueInput)
  @IsOptional()
  @Field(() => UsuarioWhereUniqueInput, {
    nullable: true,
  })
  usuario?: UsuarioWhereUniqueInput;
}

export { PedidoWhereInput as PedidoWhereInput };
