/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsNumber,
  Min,
  Max,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
  IsEnum,
  IsBoolean,
  ValidateNested,
} from "class-validator";

import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { JsonValue } from "type-fest";
import { Type } from "class-transformer";
import { EnumPedidoEstado } from "./EnumPedidoEstado";
import { EnumPedidoMetodoDePago } from "./EnumPedidoMetodoDePago";
import { Talle } from "../../talle/base/Talle";
import { Usuario } from "../../usuario/base/Usuario";

@ObjectType()
class Pedido {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  adeuda!: number | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  comprobante!: JsonValue;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  descripcion!: string | null;

  @ApiProperty({
    required: false,
    enum: EnumPedidoEstado,
  })
  @IsEnum(EnumPedidoEstado)
  @IsOptional()
  @Field(() => EnumPedidoEstado, {
    nullable: true,
  })
  estado?: "Option1" | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    enum: EnumPedidoMetodoDePago,
  })
  @IsEnum(EnumPedidoMetodoDePago)
  @IsOptional()
  @Field(() => EnumPedidoMetodoDePago, {
    nullable: true,
  })
  metodoDePago?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  restoPagado!: boolean | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  seA!: number | null;

  @ApiProperty({
    required: false,
    type: () => Talle,
  })
  @ValidateNested()
  @Type(() => Talle)
  @IsOptional()
  talle?: Talle | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: () => Usuario,
  })
  @ValidateNested()
  @Type(() => Usuario)
  @IsOptional()
  usuario?: Usuario | null;
}

export { Pedido as Pedido };
