/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { OrdenDeCompra } from "./OrdenDeCompra";
import { OrdenDeCompraCountArgs } from "./OrdenDeCompraCountArgs";
import { OrdenDeCompraFindManyArgs } from "./OrdenDeCompraFindManyArgs";
import { OrdenDeCompraFindUniqueArgs } from "./OrdenDeCompraFindUniqueArgs";
import { CreateOrdenDeCompraArgs } from "./CreateOrdenDeCompraArgs";
import { UpdateOrdenDeCompraArgs } from "./UpdateOrdenDeCompraArgs";
import { DeleteOrdenDeCompraArgs } from "./DeleteOrdenDeCompraArgs";
import { Usuario } from "../../usuario/base/Usuario";
import { OrdenDeCompraService } from "../ordenDeCompra.service";
@graphql.Resolver(() => OrdenDeCompra)
export class OrdenDeCompraResolverBase {
  constructor(protected readonly service: OrdenDeCompraService) {}

  async _ordenDeComprasMeta(
    @graphql.Args() args: OrdenDeCompraCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [OrdenDeCompra])
  async ordenDeCompras(
    @graphql.Args() args: OrdenDeCompraFindManyArgs
  ): Promise<OrdenDeCompra[]> {
    return this.service.ordenDeCompras(args);
  }

  @graphql.Query(() => OrdenDeCompra, { nullable: true })
  async ordenDeCompra(
    @graphql.Args() args: OrdenDeCompraFindUniqueArgs
  ): Promise<OrdenDeCompra | null> {
    const result = await this.service.ordenDeCompra(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => OrdenDeCompra)
  async createOrdenDeCompra(
    @graphql.Args() args: CreateOrdenDeCompraArgs
  ): Promise<OrdenDeCompra> {
    return await this.service.createOrdenDeCompra({
      ...args,
      data: {
        ...args.data,

        usuario: args.data.usuario
          ? {
              connect: args.data.usuario,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => OrdenDeCompra)
  async updateOrdenDeCompra(
    @graphql.Args() args: UpdateOrdenDeCompraArgs
  ): Promise<OrdenDeCompra | null> {
    try {
      return await this.service.updateOrdenDeCompra({
        ...args,
        data: {
          ...args.data,

          usuario: args.data.usuario
            ? {
                connect: args.data.usuario,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => OrdenDeCompra)
  async deleteOrdenDeCompra(
    @graphql.Args() args: DeleteOrdenDeCompraArgs
  ): Promise<OrdenDeCompra | null> {
    try {
      return await this.service.deleteOrdenDeCompra(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Usuario, {
    nullable: true,
    name: "usuario",
  })
  async getUsuario(
    @graphql.Parent() parent: OrdenDeCompra
  ): Promise<Usuario | null> {
    const result = await this.service.getUsuario(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
