/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  OrdenDeCompra as PrismaOrdenDeCompra,
  Usuario as PrismaUsuario,
} from "@prisma/client";

export class OrdenDeCompraServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.OrdenDeCompraCountArgs, "select">
  ): Promise<number> {
    return this.prisma.ordenDeCompra.count(args);
  }

  async ordenDeCompras(
    args: Prisma.OrdenDeCompraFindManyArgs
  ): Promise<PrismaOrdenDeCompra[]> {
    return this.prisma.ordenDeCompra.findMany(args);
  }
  async ordenDeCompra(
    args: Prisma.OrdenDeCompraFindUniqueArgs
  ): Promise<PrismaOrdenDeCompra | null> {
    return this.prisma.ordenDeCompra.findUnique(args);
  }
  async createOrdenDeCompra(
    args: Prisma.OrdenDeCompraCreateArgs
  ): Promise<PrismaOrdenDeCompra> {
    return this.prisma.ordenDeCompra.create(args);
  }
  async updateOrdenDeCompra(
    args: Prisma.OrdenDeCompraUpdateArgs
  ): Promise<PrismaOrdenDeCompra> {
    return this.prisma.ordenDeCompra.update(args);
  }
  async deleteOrdenDeCompra(
    args: Prisma.OrdenDeCompraDeleteArgs
  ): Promise<PrismaOrdenDeCompra> {
    return this.prisma.ordenDeCompra.delete(args);
  }

  async getUsuario(parentId: string): Promise<PrismaUsuario | null> {
    return this.prisma.ordenDeCompra
      .findUnique({
        where: { id: parentId },
      })
      .usuario();
  }
}
