/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { OrdenDeCompraService } from "../ordenDeCompra.service";
import { OrdenDeCompraCreateInput } from "./OrdenDeCompraCreateInput";
import { OrdenDeCompra } from "./OrdenDeCompra";
import { OrdenDeCompraFindManyArgs } from "./OrdenDeCompraFindManyArgs";
import { OrdenDeCompraWhereUniqueInput } from "./OrdenDeCompraWhereUniqueInput";
import { OrdenDeCompraUpdateInput } from "./OrdenDeCompraUpdateInput";

export class OrdenDeCompraControllerBase {
  constructor(protected readonly service: OrdenDeCompraService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: OrdenDeCompra })
  async createOrdenDeCompra(
    @common.Body() data: OrdenDeCompraCreateInput
  ): Promise<OrdenDeCompra> {
    return await this.service.createOrdenDeCompra({
      data: {
        ...data,

        usuario: data.usuario
          ? {
              connect: data.usuario,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        estado: true,
        id: true,
        updatedAt: true,

        usuario: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [OrdenDeCompra] })
  @ApiNestedQuery(OrdenDeCompraFindManyArgs)
  async ordenDeCompras(
    @common.Req() request: Request
  ): Promise<OrdenDeCompra[]> {
    const args = plainToClass(OrdenDeCompraFindManyArgs, request.query);
    return this.service.ordenDeCompras({
      ...args,
      select: {
        createdAt: true,
        estado: true,
        id: true,
        updatedAt: true,

        usuario: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: OrdenDeCompra })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async ordenDeCompra(
    @common.Param() params: OrdenDeCompraWhereUniqueInput
  ): Promise<OrdenDeCompra | null> {
    const result = await this.service.ordenDeCompra({
      where: params,
      select: {
        createdAt: true,
        estado: true,
        id: true,
        updatedAt: true,

        usuario: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: OrdenDeCompra })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOrdenDeCompra(
    @common.Param() params: OrdenDeCompraWhereUniqueInput,
    @common.Body() data: OrdenDeCompraUpdateInput
  ): Promise<OrdenDeCompra | null> {
    try {
      return await this.service.updateOrdenDeCompra({
        where: params,
        data: {
          ...data,

          usuario: data.usuario
            ? {
                connect: data.usuario,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          estado: true,
          id: true,
          updatedAt: true,

          usuario: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: OrdenDeCompra })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOrdenDeCompra(
    @common.Param() params: OrdenDeCompraWhereUniqueInput
  ): Promise<OrdenDeCompra | null> {
    try {
      return await this.service.deleteOrdenDeCompra({
        where: params,
        select: {
          createdAt: true,
          estado: true,
          id: true,
          updatedAt: true,

          usuario: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
