/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Talle } from "./Talle";
import { TalleCountArgs } from "./TalleCountArgs";
import { TalleFindManyArgs } from "./TalleFindManyArgs";
import { TalleFindUniqueArgs } from "./TalleFindUniqueArgs";
import { CreateTalleArgs } from "./CreateTalleArgs";
import { UpdateTalleArgs } from "./UpdateTalleArgs";
import { DeleteTalleArgs } from "./DeleteTalleArgs";
import { PedidoFindManyArgs } from "../../pedido/base/PedidoFindManyArgs";
import { Pedido } from "../../pedido/base/Pedido";
import { TalleService } from "../talle.service";
@graphql.Resolver(() => Talle)
export class TalleResolverBase {
  constructor(protected readonly service: TalleService) {}

  async _tallesMeta(
    @graphql.Args() args: TalleCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Talle])
  async talles(@graphql.Args() args: TalleFindManyArgs): Promise<Talle[]> {
    return this.service.talles(args);
  }

  @graphql.Query(() => Talle, { nullable: true })
  async talle(
    @graphql.Args() args: TalleFindUniqueArgs
  ): Promise<Talle | null> {
    const result = await this.service.talle(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Talle)
  async createTalle(@graphql.Args() args: CreateTalleArgs): Promise<Talle> {
    return await this.service.createTalle({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Talle)
  async updateTalle(
    @graphql.Args() args: UpdateTalleArgs
  ): Promise<Talle | null> {
    try {
      return await this.service.updateTalle({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Talle)
  async deleteTalle(
    @graphql.Args() args: DeleteTalleArgs
  ): Promise<Talle | null> {
    try {
      return await this.service.deleteTalle(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Pedido], { name: "pedidos" })
  async findPedidos(
    @graphql.Parent() parent: Talle,
    @graphql.Args() args: PedidoFindManyArgs
  ): Promise<Pedido[]> {
    const results = await this.service.findPedidos(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
