/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TalleService } from "../talle.service";
import { TalleCreateInput } from "./TalleCreateInput";
import { Talle } from "./Talle";
import { TalleFindManyArgs } from "./TalleFindManyArgs";
import { TalleWhereUniqueInput } from "./TalleWhereUniqueInput";
import { TalleUpdateInput } from "./TalleUpdateInput";
import { PedidoFindManyArgs } from "../../pedido/base/PedidoFindManyArgs";
import { Pedido } from "../../pedido/base/Pedido";
import { PedidoWhereUniqueInput } from "../../pedido/base/PedidoWhereUniqueInput";

export class TalleControllerBase {
  constructor(protected readonly service: TalleService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Talle })
  async createTalle(@common.Body() data: TalleCreateInput): Promise<Talle> {
    return await this.service.createTalle({
      data: data,
      select: {
        createdAt: true,
        especial: true,
        id: true,
        updatedAt: true,
        valor: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Talle] })
  @ApiNestedQuery(TalleFindManyArgs)
  async talles(@common.Req() request: Request): Promise<Talle[]> {
    const args = plainToClass(TalleFindManyArgs, request.query);
    return this.service.talles({
      ...args,
      select: {
        createdAt: true,
        especial: true,
        id: true,
        updatedAt: true,
        valor: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Talle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async talle(
    @common.Param() params: TalleWhereUniqueInput
  ): Promise<Talle | null> {
    const result = await this.service.talle({
      where: params,
      select: {
        createdAt: true,
        especial: true,
        id: true,
        updatedAt: true,
        valor: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Talle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTalle(
    @common.Param() params: TalleWhereUniqueInput,
    @common.Body() data: TalleUpdateInput
  ): Promise<Talle | null> {
    try {
      return await this.service.updateTalle({
        where: params,
        data: data,
        select: {
          createdAt: true,
          especial: true,
          id: true,
          updatedAt: true,
          valor: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Talle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTalle(
    @common.Param() params: TalleWhereUniqueInput
  ): Promise<Talle | null> {
    try {
      return await this.service.deleteTalle({
        where: params,
        select: {
          createdAt: true,
          especial: true,
          id: true,
          updatedAt: true,
          valor: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/pedidos")
  @ApiNestedQuery(PedidoFindManyArgs)
  async findPedidos(
    @common.Req() request: Request,
    @common.Param() params: TalleWhereUniqueInput
  ): Promise<Pedido[]> {
    const query = plainToClass(PedidoFindManyArgs, request.query);
    const results = await this.service.findPedidos(params.id, {
      ...query,
      select: {
        adeuda: true,
        comprobante: true,
        createdAt: true,
        descripcion: true,
        estado: true,
        id: true,
        metodoDePago: true,
        restoPagado: true,
        seA: true,

        talle: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        usuario: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/pedidos")
  async connectPedidos(
    @common.Param() params: TalleWhereUniqueInput,
    @common.Body() body: PedidoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pedidos: {
        connect: body,
      },
    };
    await this.service.updateTalle({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/pedidos")
  async updatePedidos(
    @common.Param() params: TalleWhereUniqueInput,
    @common.Body() body: PedidoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pedidos: {
        set: body,
      },
    };
    await this.service.updateTalle({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/pedidos")
  async disconnectPedidos(
    @common.Param() params: TalleWhereUniqueInput,
    @common.Body() body: PedidoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pedidos: {
        disconnect: body,
      },
    };
    await this.service.updateTalle({
      where: params,
      data,
      select: { id: true },
    });
  }
}
