/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Talle as PrismaTalle,
  Pedido as PrismaPedido,
} from "@prisma/client";

export class TalleServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.TalleCountArgs, "select">): Promise<number> {
    return this.prisma.talle.count(args);
  }

  async talles(args: Prisma.TalleFindManyArgs): Promise<PrismaTalle[]> {
    return this.prisma.talle.findMany(args);
  }
  async talle(args: Prisma.TalleFindUniqueArgs): Promise<PrismaTalle | null> {
    return this.prisma.talle.findUnique(args);
  }
  async createTalle(args: Prisma.TalleCreateArgs): Promise<PrismaTalle> {
    return this.prisma.talle.create(args);
  }
  async updateTalle(args: Prisma.TalleUpdateArgs): Promise<PrismaTalle> {
    return this.prisma.talle.update(args);
  }
  async deleteTalle(args: Prisma.TalleDeleteArgs): Promise<PrismaTalle> {
    return this.prisma.talle.delete(args);
  }

  async findPedidos(
    parentId: string,
    args: Prisma.PedidoFindManyArgs
  ): Promise<PrismaPedido[]> {
    return this.prisma.talle
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .pedidos(args);
  }
}
