/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProductoService } from "../producto.service";
import { ProductoCreateInput } from "./ProductoCreateInput";
import { Producto } from "./Producto";
import { ProductoFindManyArgs } from "./ProductoFindManyArgs";
import { ProductoWhereUniqueInput } from "./ProductoWhereUniqueInput";
import { ProductoUpdateInput } from "./ProductoUpdateInput";

export class ProductoControllerBase {
  constructor(protected readonly service: ProductoService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Producto })
  async createProducto(
    @common.Body() data: ProductoCreateInput
  ): Promise<Producto> {
    return await this.service.createProducto({
      data: data,
      select: {
        colorPrincipal: true,
        createdAt: true,
        esLiso: true,
        genero: true,
        id: true,
        nombre: true,
        precio: true,
        stock: true,
        subColorVivo: true,
        tipo: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Producto] })
  @ApiNestedQuery(ProductoFindManyArgs)
  async productos(@common.Req() request: Request): Promise<Producto[]> {
    const args = plainToClass(ProductoFindManyArgs, request.query);
    return this.service.productos({
      ...args,
      select: {
        colorPrincipal: true,
        createdAt: true,
        esLiso: true,
        genero: true,
        id: true,
        nombre: true,
        precio: true,
        stock: true,
        subColorVivo: true,
        tipo: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Producto })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async producto(
    @common.Param() params: ProductoWhereUniqueInput
  ): Promise<Producto | null> {
    const result = await this.service.producto({
      where: params,
      select: {
        colorPrincipal: true,
        createdAt: true,
        esLiso: true,
        genero: true,
        id: true,
        nombre: true,
        precio: true,
        stock: true,
        subColorVivo: true,
        tipo: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Producto })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProducto(
    @common.Param() params: ProductoWhereUniqueInput,
    @common.Body() data: ProductoUpdateInput
  ): Promise<Producto | null> {
    try {
      return await this.service.updateProducto({
        where: params,
        data: data,
        select: {
          colorPrincipal: true,
          createdAt: true,
          esLiso: true,
          genero: true,
          id: true,
          nombre: true,
          precio: true,
          stock: true,
          subColorVivo: true,
          tipo: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Producto })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProducto(
    @common.Param() params: ProductoWhereUniqueInput
  ): Promise<Producto | null> {
    try {
      return await this.service.deleteProducto({
        where: params,
        select: {
          colorPrincipal: true,
          createdAt: true,
          esLiso: true,
          genero: true,
          id: true,
          nombre: true,
          precio: true,
          stock: true,
          subColorVivo: true,
          tipo: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
